version: "3.7"

services:
  db:
    image: mysql
    container_name: db-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
     - "3306:3306"
 #  volumes:
  #    - ./

  back-end:
    image: node
    container_name: back-end-node
    restart: always
    depends_on:
     - db
    ports:
     - "3000:3000"
 #  volumes:
  #    - ./

  reconhecimento:
    image: javascript
    container_name: reconhecimento-js    
    restart: always
    depends_on:
     - back-end
    ports:
     - "3002:3002"
 #  volumes:
  #    - ./

  front-end:
    image: react
    container_name: front-end-react
    restart: always
    depends_on:
     - front-end
    ports:
     - "3001:3001"
 #  volumes:
  #    - ./
      

